import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../core/repositories/quran_repository.dart';
import '../../core/repositories/tafsir_repository.dart';
import '../../core/settings/app_settings.dart';
import '../../core/theme/islam307_theme.dart';
import 'tafsir_attribution.dart';

class TafsirScreen extends ConsumerStatefulWidget {
  const TafsirScreen({super.key});

  @override
  ConsumerState<TafsirScreen> createState() => _TafsirScreenState();
}

class _TafsirScreenState extends ConsumerState<TafsirScreen> {
  final _tafsirRepo = TafsirRepository();
  final _quranRepo = QuranRepository();
  List<Map<String, dynamic>> _sources = [];
  List<Map<String, dynamic>> _surahs = [];
  String? _slug;
  int _surah = 1;
  int _ayah = 1;
  int _maxAyah = 7;
  Map<String, dynamic>? _entry;
  bool _loading = true;
  bool _loadingEntry = false;

  @override
  void initState() {
    super.initState();
    _boot();
  }

  Future<void> _boot() async {
    final sources = await _tafsirRepo.catalogSources();
    final surahs = await _quranRepo.surahs();
    final preferred = ref.read(appSettingsProvider).preferredTafsirSlug;
    final available = sources.where((s) => s['available'] == true).toList();
    final slug = sources.any((s) => s['slug'] == preferred)
        ? preferred
        : (available.isNotEmpty
            ? available.first['slug'] as String
            : sources.first['slug'] as String);
    if (!mounted) return;
    setState(() {
      _sources = sources;
      _surahs = surahs;
      _slug = slug;
      _maxAyah = (surahs.firstWhere((s) => s['number'] == 1)['ayah_count'] as int?) ?? 7;
      _loading = false;
    });
    await _loadEntry();
  }

  Future<void> _loadEntry() async {
    if (_slug == null) return;
    setState(() => _loadingEntry = true);
    final entry = await _tafsirRepo.entry(_slug!, _surah, _ayah);
    if (!mounted) return;
    setState(() {
      _entry = entry;
      _loadingEntry = false;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Tafsir', style: TextStyle(fontWeight: FontWeight.w800)),
        leading: IconButton(icon: const Icon(Icons.arrow_back_ios_new_rounded, size: 20), onPressed: () => context.pop()),
      ),
      body: _loading
          ? const Center(child: CircularProgressIndicator(color: Islam307Theme.emerald))
          : ListView(
              padding: const EdgeInsets.all(20),
              children: [
                const Text(
                  'Select an official Tafseer API source. No bundled Tafseer files are used, and content is never generated by AI.',
                  style: TextStyle(color: Islam307Theme.textMuted, height: 1.5),
                ),
                const SizedBox(height: 16),
                DropdownButtonFormField<String>(
                  value: _slug,
                  decoration: const InputDecoration(labelText: 'Tafsir source'),
                  items: _sources
                      .map((s) => DropdownMenuItem(
                            value: s['slug'] as String,
                            child: Text(
                              '${s['name_en']}${s['available'] == true ? ' · official API' : ' · unavailable'}',
                            ),
                          ))
                      .toList(),
                  onChanged: (v) async {
                    if (v == null) return;
                    setState(() => _slug = v);
                    await ref.read(appSettingsProvider.notifier).setPreferredTafsir(v);
                    await _loadEntry();
                  },
                ),
                const SizedBox(height: 12),
                DropdownButtonFormField<int>(
                  value: _surah,
                  decoration: const InputDecoration(labelText: 'Surah'),
                  items: _surahs
                      .map((s) => DropdownMenuItem(
                            value: s['number'] as int,
                            child: Text('${s['number']}. ${s['name_en']}'),
                          ))
                      .toList(),
                  onChanged: (v) async {
                    if (v == null) return;
                    final s = _surahs.firstWhere((x) => x['number'] == v);
                    setState(() {
                      _surah = v;
                      _maxAyah = s['ayah_count'] as int;
                      _ayah = 1;
                    });
                    await _loadEntry();
                  },
                ),
                const SizedBox(height: 12),
                DropdownButtonFormField<int>(
                  value: _ayah > _maxAyah ? 1 : _ayah,
                  decoration: const InputDecoration(labelText: 'Ayah'),
                  items: List.generate(_maxAyah, (i) => i + 1)
                      .map((n) => DropdownMenuItem(value: n, child: Text('$n')))
                      .toList(),
                  onChanged: (v) async {
                    if (v == null) return;
                    setState(() => _ayah = v);
                    await _loadEntry();
                  },
                ),
                const SizedBox(height: 20),
                if (_loadingEntry)
                  const Center(child: CircularProgressIndicator(color: Islam307Theme.emerald))
                else if (_entry == null || _entry!['unavailable'] == true)
                  Card(
                    child: Padding(
                      padding: const EdgeInsets.all(16),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(_entry?['message'] as String? ?? TafsirRepository.unavailableMessage,
                              style: const TextStyle(fontWeight: FontWeight.w800, color: Colors.orange)),
                          const SizedBox(height: 8),
                          Text('${_entry?['notes'] ?? ''}', style: const TextStyle(color: Islam307Theme.textMuted)),
                        ],
                      ),
                    ),
                  )
                else
                  Card(
                    child: Padding(
                      padding: const EdgeInsets.all(16),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text('${_entry!['source_name']} · $_surah:$_ayah',
                              style: const TextStyle(fontWeight: FontWeight.w800, color: Islam307Theme.emeraldDeep)),
                          const SizedBox(height: 12),
                          Text('${_entry!['text']}', style: const TextStyle(height: 1.7, fontSize: 15)),
                          const SizedBox(height: 16),
                          TafsirAttribution(entry: _entry!),
                        ],
                      ),
                    ),
                  ),
              ],
            ),
    );
  }
}
